env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  prettier/prettier: warn
settings:
  react:
    version: detect
  import/resolver:
    node:
      paths: ["src"],
      extensions: [".js", ".jsx", ".ts", ".tsx"]